### ISSUE TITLE
在某科学版本使用会闪退

### ISSUE THREAD

**Issue by HornBike** [ERR0RPR0MPT/maimai-windows-touch-panel#2]
触摸检查1p好2p无
游戏进行到选择游戏模式后闪退
是a-cs.dll的问题么，需要修改哪些部分

**Comment by ERR0RPR0MPT** [comment]
下个非改版的hdd吧

**Comment by HornBike** [comment]
我用的是最早emu上的1.30
自己一点点装opt升级上来的
应该是非改版的吧
是tools不干净吗

**Comment by HornBike** [comment]
dummypanel可以跑的，应该是a-cs.dll的问题，但是我找了很久找不到相应的代码在哪改

**Comment by HornBike** [comment]
ok自己解决了 很奇怪的原因
一定要登陆账号，不能用游客模式😅
