### ISSUE TITLE
maimai-windows-touch-panel无法保持最顶层窗口

### ISSUE THREAD

**Issue by Pennages** [ERR0RPR0MPT/maimai-windows-touch-panel#5]
hdd启动后，能够正常连接到游戏，但是游戏内触摸没有反应，将游戏移动到一边后，便能正常触摸（图三）。后面大概看了下，是因为hdd窗口位于最顶层，maimai-windows-touch-panel被挤到下一层去了。。。
![屏幕截图(217)](https://github.com/user-attachments/assets/8b30335e-e6f4-4ee4-a12e-953d76308c5a)
![屏幕截图(218)](https://github.com/user-attachments/assets/ac596dc7-fbb5-4cc3-958a-92b41f3feaa2)
![IMG_20240902_191602_lmc_8 4](https://github.com/user-attachments/assets/4640b4de-c90a-474e-9f9b-5ec447c7152b)
![IMG_20240902_191744_lmc_8 4](https://github.com/user-attachments/assets/5dea6d30-0504-4d95-9102-0b3985ce544d)

已按照要求做好设置
没有对config.yaml作修改(默认)

**Comment by DanielToyama** [comment]
建议使用工具PowerToys强制保持窗口置顶
PS：这个东西理论上是不需要置顶的，因为如果他和你的屏幕分辨率一样大，是可以直接盖住整个屏幕的，不强制置顶是方便你切换

**Comment by DanielToyama** [comment]
如果hdd自动置顶的话可能需要另外找办法关闭置顶，默认应该是不会置顶的

**Comment by Pennages** [comment]
> 建议使用工具PowerToys强制保持窗口置顶 PS：这个东西理论上是不需要置顶的，因为如果他和你的屏幕分辨率一样大，是可以直接盖住整个屏幕的，不强制置顶是方便你切换

豪得我尝试用下powertoy置顶下。

**Comment by Pennages** [comment]
> 建议使用工具PowerToys强制保持窗口置顶 PS：这个东西理论上是不需要置顶的，因为如果他和你的屏幕分辨率一样大，是可以直接盖住整个屏幕的，不强制置顶是方便你切换

可行，非常感谢
